// frontend/components/homePage/liveSoccer.tsx
import React from 'react'

const LiveSoccer = () => {
    return (
        <div className="MYDeg w-full bg-[#ffffff] rounded-2xl px-3 py-8 text-sm">
            <p>
                Live soccer results page on Sofascore offers real-time soccer scores of all live matches that are being
                played. Sofascore covers hundreds of soccer leagues, cups and tournaments with live updated results,
                statistics, league tables, video highlights and fixtures. From most popular soccer leagues (
                <button className="text-blue-400">UEFA ChampionsLeague</button>,
                <button className="text-blue-400">Premier League</button>,
                <button className="text-blue-400">UEFA Europa League</button>,
                <button className="text-blue-400">Ligue 1</button>,
                <button className="text-blue-400">Serie A</button>,
                <button className="text-blue-400">Bundesliga</button>,
                <button className="text-blue-400">LaLiga</button>,
                <button className="text-blue-400">Brasileiro Série A</button>,)
                top
                players ratings and statistics to soccer games played today, our soccer live score page covers all the
                information you need.
            </p>
        </div>
    )
}

export default LiveSoccer

// src/components/LiveSoccer.vue
<template>
    <div class="MYDeg w-full bg-[#ffffff] rounded-2xl px-3 py-8 text-sm">
        <p>
            Live soccer results page on Sofascore offers real-time soccer scores of all live matches that are being
            played. Sofascore covers hundreds of soccer leagues, cups and tournaments with live updated results,
            statistics, league tables, video highlights and fixtures. From most popular soccer leagues (
            <button class="text-blue-400">UEFA ChampionsLeague</button>,
            <button class="text-blue-400">Premier League</button>,
            <button class="text-blue-400">UEFA Europa League</button>,
            <button class="text-blue-400">Ligue 1</button>,
            <button class="text-blue-400">Serie A</button>,
            <button class="text-blue-400">Bundesliga</button>,
            <button class="text-blue-400">LaLiga</button>,
            <button class="text-blue-400">Brasileiro Série A</button>,)
            top
            players ratings and statistics to soccer games played today, our soccer live score page covers all the
            information you need.
        </p>
    </div>
</template>
