// components/homePage/Topleagues.tsx
import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import DisplayImage from '@/utils/displayImage'


export interface TopleaguesApi {
    uniqueTournaments: Array<TopleaguesAPIJson>
}

export interface TopleaguesAPIJson {
    name: string
    slug: string
    primaryColorHex: string
    secondaryColorHex: string
    category: {
        name: string
        slug: string
        sport: {
            name: string
            slug: string
            id: Number
        },
        id: Number
        flag: string
    },
    userCount: Number
    id: Number
    displayInverseHomeAwayTeams: boolean
}


const Topleagues = () => {
    const [leagues, setLeagues] = useState<Array<TopleaguesAPIJson>>([])
    useEffect(() => {
        (
            async () => {
                try {
                    const response = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/config/top-unique-tournaments/MA/football`, {})
                    if (response.ok) {
                        const data: TopleaguesApi = await response.json()
                        setLeagues(data.uniqueTournaments)
                    }
                } catch (error) {

                }
            }
        )()
    }, [])
    return (
        < div className="MYDeg   space-y-1 pb-4  rounded-2xl bg-white" >
            <div className=" p-4 font-medium text-black">Top leagues</div>
            {leagues.map((item, index) =>
                <Link key={index} href={`/ma/tournament/soccer/${item.category.slug}/${item.slug}/${item.id}`} className="w-full flex   items-center  px-5 py-0.5 space-x-5 hover:bg-slate-100"                >
                    <DisplayImage onErrorImage='tournament' alt='' width={25} height={25} src={`https://sofascore.com/api/v1/unique-tournament/${item.id}/image`} />
                    <div className="text-[16px] font-thin opacity-90">
                        {item.name}
                    </div>
                </Link>
            )}
        </div >
    )
}
export default Topleagues

// src/components/Topleagues.vue
<template class="">
    <div class="MYDeg   space-y-1 pb-4  rounded-2xl bg-white">
        <div class=" p-4 font-medium text-black">Top leagues</div>
        <button class="w-full flex   items-center  px-5 py-0.5 space-x-5 hover:bg-slate-100"
            v-for="(item, index) in leagues" :key="index">
            <img class="w-5" src="../assets/ufa.png" alt="">
            <div class="text-[16px] font-thin opacity-90">
                {{ item }}
            </div>
        </button>
    </div>
</template>

<script>
export default {
    data() {
        return {
            leagues: [
                'UEFA Champions League',
                'UEFA Europa League',
                'Premier League',
                'LaLiga',
                'Bundesliga',
                'Serie A',
                'Ligue 1',
                'Eredivisie',
                'Brasileirão Série A',
                'CONMEBOL Libertadores',
                'CAF Champions League',
                'Botola Pro',
                'World Championship'
            ]

        }
    },
}

</script>

<style scoped>
.MYDeg {
    box-shadow: 0 1px 4px rgba(34, 34, 38, 0.08);
}
</style>
