// frontend/components/homePage/TopPlayers.tsx
import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import Shimmer_topPlayer from '../shimmer/shi2_topPlayer'
import { TopPlayersAPIJson } from '@/interface/api/topPlayers'
import DisplayRating from '@/utils/displayRating'
import DisplayImage from '@/utils/displayImage'
import Image from 'next/image'

const TopPlayers = () => {

    const [waitdata, setWaitdata] = useState(true)
    const [topPlayers, settopPlayers] = useState<TopPlayersAPIJson[]>([])
    const [ShowMore, setShowMore] = useState(false)
    useEffect(() => {
        (
            async () => {
                const response = await fetch(`https://sofascore.com/api/v1/sport/football/trending-top-players`, {});
                if (response.ok) {
                    const data = await response.json()
                    settopPlayers(Array.from(data.topPlayers))
                    setWaitdata(false)
                }
            }
        )()
    }, [])

    return (
        <div className="MYDeg  w-full bg-[#ffffff] rounded-2xl  space-y-2 ">
            <div className=" text-slate-800 p-3 border-b-[1px] border-gray-300">
                <p className=" text-[20px]">Top players</p>
                <p className=" text-gray-900 text-sm opacity-35">Best rated players from recent matches</p>
            </div>
            <div className="">
                {topPlayers.slice(0, ShowMore ? topPlayers.length : 5).map((item, index) =>
                    <div key={index} >
                        <Link href={`/ma/player/${item.player.slug}/${item.player.id}`} className="flex space-x-2 items-center  px-2 text-gray-900 text-opacity-75 hover:bg-custom-default-hover">
                            <div className="text-[12px] w-5">{index + 1}</div>
                            <div className=" w-14  relative">
                                <DisplayImage onErrorImage='player' width={400} height={400} className=" border-[1px]  border-gray-300 bg-slate-500  w-14 rounded-full" src={`https://api.sofascore.app/api/v1/player/${item.player.id}/image`} alt="" />
                                <DisplayImage onErrorImage='player' className=" absolute  bottom-0 right-0 w-5" width={400} height={400} src={`https://sofascore.com/api/v1/team/${item.team.id}/image/`} alt="" />
                            </div>
                            <div className={`w-full flex  items-center p-2 ${index == 0 ? '' : 'border-b-1 '}`}>
                                <div className="w-full flex flex-col justify-center ">
                                    <p>{item.player.name}</p>
                                    <p className="text-gray-900 opacity-35 text-[12px] truncate">{item.event.homeTeam.shortName} vs {item.event.awayTeam.shortName}</p>
                                </div>
                                <DisplayRating rating={item.rating} type='in' />
                                {/* <div className="bg-[#037ab0] h-full w-8 p-0.5 rounded-[4px] text-[14px] text-white text-center ">{item.rating}</div> */}
                            </div>
                        </Link>
                        {

                            index == 0 && <div className="w-full p-2 absolut">
                                <Image className=" object-contain rounded-3xl" src="/image/map-sofascore.jpeg" alt="" />
                            </div>
                        }
                    </div>
                )}
            </div>
            <div className={`${waitdata ? 'hidden' : 'block'} w-full p-3 flex space-x-2  justify-end items-center`}>
                <button onClick={() => setShowMore((prv) => !prv)} className=" flex space-x-2 items-center">
                    <div className=" font-medium text-blue-600 ">
                        {ShowMore ? 'Show less' : 'Show more'}
                    </div>
                    <Image className={` w-4 ${ShowMore ? 'rotate-90 ' : '-rotate-90'}`} src="/image/blue-arraw.svg" alt="" />
                </button>
            </div>
            {

                waitdata && <Shimmer_topPlayer />
            }
        </div >
    )
}

export default TopPlayers

// src/components/TopPlayers.vue
<template>
    <div class="MYDeg w-full bg-[#ffffff] rounded-2xl  space-y-2 ">
        <div class=" text-slate-800 p-3 border-b-[1px] border-gray-300">
            <p class=" text-[20px]">Top players</p>
            <p class=" text-gray-900 text-sm opacity-35">Best rated players from recent matches</p>
        </div>
        <div v-if="waitdata" class="">
            <div v-for="(item, index) in topPlayers.slice(0, 1) "
                class="flex space-x-2 items-center   px-2 text-gray-900 text-opacity-75">
                <div class="text-[12px]">{{ index + 1 }}</div>
                <div class=" w-14  relative">
                    <img class=" object-contain rounded-full" src="/src/assets/messi.jpg" alt="">
                    <img class=" absolute  bottom-0 right-0 w-5" src="/src/assets/club.png" alt="">
                </div>
                <div class="w-full flex  items-center  p-2">
                    <div class="w-full flex flex-col justify-center ">
                        <p>{{ item.name }}</p>
                        <p class="text-gray-900 opacity-35 text-[14px]">{{ item.match }}</p>
                    </div>
                    <div class="bg-[#037ab0] h-full p-0.5  rounded-md text-white ">{{ item.rating }}</div>
                </div>
            </div>
            <div class="w-full p-2">
                <img class=" object-contain rounded-3xl" src="/src/assets/map-sofascore.jpeg" alt="">
            </div>
            <div v-for="(item, index) in topPlayers.slice(1)"
                class="flex space-x-2 items-center  px-2 text-gray-900 text-opacity-75">
                <div class="text-[12px]">{{ index + 1 }}</div>
                <div class=" w-14  relative">
                    <img class=" object-contain rounded-full" src="/src/assets/messi.jpg" alt="">
                    <img class=" absolute  bottom-0 right-0 w-5" src="/src/assets/club.png" alt="">
                </div>
                <div class="w-full flex  items-center  border-b-2 p-2">
                    <div class="w-full flex flex-col justify-center ">
                        <p>{{ item.name }}</p>
                        <p class="text-gray-900 opacity-35 text-[14px]">{{ item.match }}</p>
                    </div>
                    <div class="bg-[#037ab0] h-full p-0.5  rounded-md text-white ">{{ item.rating }}</div>
                </div>
            </div>
            <div class="p-3 flex space-x-2  justify-end items-center">
                <div class=" font-medium text-blue-600 ">
                    Show more
                </div>
                <img class=" w-4" src="/src/assets/ball.svg" alt="">
            </div>
        </div>


        <!-- shimmer -->
        <div v-if="!waitdata" class="animate-pulse">
            <div v-for="(item, index) in topPlayers.slice(0, 1) "
                class="flex space-x-2 items-center   px-2 text-gray-900 text-opacity-75">
                <div class=" w-14  relative">
                    <div class="w-10 h-10 rounded-full bg-slate-200"></div>
                </div>
                <div class="w-full space-y-2 p-2">
                    <div class="w-20 h-2 bg-slate-200"></div>
                    <div class="w-24 h-2 bg-slate-200"></div>
                </div>
            </div>
            <div class="w-full h-64  p-2">
                <div class="flex bg-slate-200 w-full h-full rounded-xl"></div>
            </div>
            <div v-for="(item, index) in topPlayers.slice(1)"
                class="flex space-x-2 items-center py-3   px-2 text-gray-900 text-opacity-75">
                <div class=" w-14  relative">
                    <div class="w-10 h-10 rounded-full bg-slate-200"></div>
                </div>
                <div class="w-full space-y-2 p-2">
                    <div class="w-20 h-2 bg-slate-200"></div>
                    <div class="w-24 h-2 bg-slate-200"></div>
                </div>
            </div>
            <div class="p-3 flex space-x-2  justify-end items-center">
                <div class=" font-medium text-blue-600 ">
                    Show more
                </div>
                <img class=" w-4" src="/src/assets/ball.svg" alt="">
            </div>
        </div>
    </div>
</template>
<script>
export default {
    mounted() {
        setTimeout(() => {
            this.waitdata = true;
        }, 1500);
    },
    data() {
        return {
            waitdata: false,

            topPlayers: [
                {
                    name: 'Lionel Messi',
                    rating: 9.5,
                    match: 'La Liga Match',
                    match: 'Barcelona vs. Real Madrid'
                },
                {
                    name: 'Cristiano Ronaldo',
                    rating: 9.4,
                    match: 'Serie A Match',
                    match: 'Juventus vs. Inter Milan'
                },
                {
                    name: 'Neymar Jr.',
                    rating: 9.3,
                    match: 'Ligue 1 Match',
                    match: 'PSG vs. Olympique Marseille'
                },
                {
                    name: 'Robert Lewandowski',
                    rating: 9.6,
                    match: 'Bundesliga Match',
                    match: 'Bayern Munich vs. Borussia Dortmund'
                },
                {
                    name: 'Kevin De Bruyne',
                    rating: 9.5,
                    match: 'Premier League Match',
                    match: 'Manchester City vs. Liverpool'
                },
                {
                    name: 'Kylian Mbappé',
                    rating: 9.4,
                    match: 'Champions League Match',
                    match: 'PSG vs. Real Madrid'
                },
                {
                    name: 'Virgil van Dijk',
                    rating: 9.3,
                    match: 'UEFA Euro Qualifier',
                    match: 'Netherlands vs. Germany'
                },
                {
                    name: 'Sadio Mané',
                    rating: 9.2,
                    match: 'FA Cup Match',
                    match: 'Liverpool vs. Chelsea'
                },
            ]
        };
    }
}
</script>
